---
ruby_version: 2.3.1
ruby_install_from_source: true
ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.gz
git_packages:
  - git
extra_path: /opt/fits:/opt/kakadu
deploy_user_uid: 1002
deploy_ssh_users:
  - name: tpendragon
    key: https://github.com/tpendragon.keys
  - name: kevin.reiss
    key: https://github.com/kevinreiss.keys
  - name: eliot.jordan
    key: https://github.com/eliotjordan.keys
  - name: jpstroop
    key: https://github.com/jpstroop.keys
  - name: heaven
    key: "{{lookup('file', 'keys/heaven.pub')}}"
  - name: tampakis
    key: https://github.com/tampakis.keys
