---
postgres_host: "127.0.0.1"
postgresql_is_cloud: true
generic_app_user: "confluence"
postgresql_is_local: true
postgres_version: 11
application_dbuser_name: "confluence"
application_db_name: "confluence_db"
application_dbuser_password: "{{ confluence_db_password }}"
application_dbuser_role_attr_flags: "SUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION"
db_clusteradmin_password: "{{ vault_postgres_admin_password }}"
db_clusteradmin_user: "postgres"
postgres_port: "{{ confluence_db_port }}"
postgres_admin_user: "{{ db_clusteradmin_user }}"
postgres_admin_password: "{{ db_clusteradmin_password }}"
confluence_db_port: 5432
confluence_db_password: "{{ vault_confluence_db_password }}"
