---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: "Ensure that the system packages are installed"
    package:
      name: "{{ item }}"
      state: present
    check_mode: true
    register: pkg_status
    loop:
      - libmysqlclient-dev
  - name: "Ensure that the MySQL user and database exist"
    command: "mysql --user=oawaiver --password=oawaiver --execute='SHOW TABLES' oawaiver"
    register: mysql_query_results
    changed_when: false
    failed_when:
      - "mysql_query_results is search(\"ERROR \")"
  - name: "Ensure that the directory structure for the Rails app. is created"
    stat:
      path: "/opt/oawaiver"
    register: oawaiver_directory
    failed_when:
      - "not oawaiver_directory.stat.exists"
      - "not oawaiver_directory.stat.isdir"
      - "not oawaiver_directory.stat.pw_name == 'deploy'"
      - "not oawaiver_directory.stat.gr_name == 'deploy'"
      - "not oawaiver_directory.stat.mode == 0755"
  - name: "Ensure that the directory structure for Capistrano deployments is created"
    stat:
      path: "{{ item }}"
    loop:
      - "/opt/oawaiver/shared/bundle"
      - "/opt/oawaiver/shared/log"
    register: capistrano_shared_dir
    failed_when:
      - "not capistrano_shared_dir.stat.exists"
      - "not capistrano_shared_dir.stat.isdir"
      - "not capistrano_shared_dir.stat.pw_name == 'deploy'"
      - "not capistrano_shared_dir.stat.gr_name == 'deploy'"
      - "not capistrano_shared_dir.stat.mode == 0775"
