---
- name: nodejs | Add upstream Yarn APT key yarn
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  register: yarn_servers
  ignore_errors: true

- name: nodejs | Add upstream Yarn APT key from sks-keyservsers
  apt_key:
    id: "{{ nodejs__yarn_upstream_key_id }}"
    keyserver: "hkp://pool.sks-keyservers.net"
    state: present
  register: yarnpool_servers
  when: yarn_servers is failed
  ignore_errors: true

- name: nodejs | Add upstream Yarn APT key from MIT
  apt_key:
    id: "{{ nodejs__yarn_upstream_key_id }}"
    state: present
    keyserver: "pgp.mit.edu"
  when: yarnpool_servers is failed
  register: yarnmit_servers
  ignore_errors: true

- name: nodejs | Add upstream Yarn APT key from PGP
  apt_key:
    id: "{{ nodejs__yarn_upstream_key_id }}"
    state: present
    keyserver: "keyserver.pgp.com"
  when: yarnmit_servers is failed
  ignore_errors: true

- name: nodejs | Add upstream Yarn APT repository
  apt_repository:
    repo: "{{ nodejs__yarn_upstream_repository }}"
    state: present
    update_cache: true
  ignore_errors: true

- name: nodejs | uninstall any apt installed node
  apt:
    name: ["nodejs"]
    state: absent

- name: nodejs | download nodejs version
  ansible.builtin.unarchive:
    src: "{{ nodejs_release_url }}/{{ desired_version }}/node-{{ desired_version }}-linux-x64.tar.gz"
    dest: /usr/local/bin
    remote_src: true

- name: nodejs | Install yarn packages
  apt:
    name: ["yarn"]
    state: present
