---
vireo_db_user: 'vireo_db_user'
vireo_db_password: "{{ vault_vireo_production_db_password }}"
vireo_db_name: 'vireo_db'
vireo_db_port: '5432'

db_host: 'lib-postgres-prod1.princeton.edu'
db_clusteradmin_password: "{{ vault_postgres_admin_password }}"
db_clusteradmin_user: "postgres"

postgres_port: "{{ vireo_db_port }}"
postgres_admin_user: "{{ db_clusteradmin_user }}"
postgres_admin_password: "{{ db_clusteradmin_password }}"
postgresql_is_local: false
postgres_version: 13
postgres_host: "lib-postgres-prod1.princeton.edu"
postfix_relayhost: "[lib-ponyexpr.princeton.edu]"

vireo_tomcat_password: "{{ vault_vireo_production_tomcat_password }}"

application_fqdn: "https://vireo.princeton.edu"

# Note that shib_hostname must be the FQDN as configured by the load balancer,
# but must NOT include the https prefix. This is the hostname as it appears to
# the OIT shibboleth auth service.
shib_hostname: "vireo.princeton.edu"
shib_host: "vireo"
