---
galaxy_info:
  role_name: apache_ant
  company: Princeton University Library
  description: Apache Ant
  author: pulibrary

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - 18.04
dependencies:
  - role: "openjdk"
