---
# tasks file for roles/oawaiver
- name: Create capistrano directory structure
  file:
    path: "{{ capistrano_directory }}/{{ item }}"
    state: "directory"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0775
  changed_when: false
  with_items:
    - "{{ capistrano_directory }}/shared/bundle"
    - "{{ capistrano_directory }}/shared/log"
