---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ouranos"
      include_role:
        name: "ouranos"
  vars:
    - running_on_server: false
    - nodejs__upstream_release: 'node_12.x'
    - nodejs__upstream_key_id: '68576280'
