---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Redis installed
    shell: 'redis-server --version | grep "Redis server"'
    register: result
    failed_when: result.rc != 0
    changed_when: false
