---
- name: Converge
  hosts: all
  vars:
    - running_on_server: false
    - deploy_user: "dspace"
    - nginx_type: opensource
    - nginx_install_from: nginx_repository
    - postgresql_is_local: false
    - postgres_host: "localhost"
    - postgres_port: "5432"
    - postgres_admin_user: "postgres"
    - postgres_admin_password: "VoightKampff"
    - shib_hostname: "instance"
  become: true
  tasks:
    - name: "Include postgresql"
      include_role:
        name: postgresql
    - name: "Include dataspace"
      include_role:
        name: dataspace
