---
- name: Converge
  hosts: all
  vars:
    - running_on_server: false
    - passenger_listen_port: '8080'
    - rails_app_directory: 'approvals'
    - rails_app_name: 'approvals'
    - install_mailcatcher: true
  become: true
  tasks:
    - name: "Include approvals"
      include_role:
        name: approvals
