---
ojs_db_user: 'ojs_dev_db_user'
ojs_db_password: "{{ vault_ojs_dev_db_password }}"
ojs_db_name: 'ojs_dev_db'
ojs_db_port: '5432'
sudo_options: "ALL=(ALL) NOPASSWD: /bin/chown"

php_version: '7.4'

ojs_admin_login: 'ojsadmin'
ojs_admin_email: 'bess.sadler@princeton.edu'

# Note that ojs_version must match one of the downloadable packages from
# https://pkp.sfu.ca/ojs/ojs_download/
ojs_version: "3.3.0-8"

db_clusteradmin_password: "{{ vault_postgres_admin_password }}"
db_clusteradmin_user: "postgres"

postgres_port: "{{ ojs_db_port }}"
postgres_admin_user: "{{ db_clusteradmin_user }}"
postgres_admin_password: "{{ db_clusteradmin_password }}"
postgresql_is_local: false
postgres_version: 13
postgres_host: "lib-postgres-staging1.princeton.edu"
postfix_relayhost: "[lib-ponyexpr.princeton.edu]"
