---
# by default this playbook runs in the staging environment
# to run in production, pass '-e runtime_env=production'
- name: build the Absolute Identifier Management site
  hosts: abid_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true
  vars_files:
    - ../site_vars.yml
    - ../group_vars/abid/{{ runtime_env | default('staging') }}.yml
    - ../group_vars/abid/vault.yml
  roles:
    - role: roles/ruby
    - role: roles/abid

  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "{{ inventory_hostname }} completed"
        channel: #server-alerts
