---
- hosts: lockers_and_study_spaces_staging
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/lockers_and_study_spaces/lockers_and_study_spaces_staging.yml
    - ../group_vars/lockers_and_study_spaces/vault.yml
  roles:
    - role: roles/lockers_and_study_spaces

  post_tasks:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "{{ inventory_hostname }} completed"
        channel: #server-alerts
