---
# best practice is to run on a single host with '--limit' for example `ansible-playbook -v --limit lib-adc2.princeton.edu playbooks/nginxplus_production.yml`
# to update configuration for existing sites, run with '-t update_conf' for example `ansible-playbook -v --limit lib-adc2.princeton.edu playbooks/nginxplus_production.yml -t update_conf`
# to replace SSL certificates and keys, run with `-t SSL`

- name: update nginx
  hosts: nginxplus
  remote_user: pulsys
  strategy: linear
  become: true

# updates existing load balancer
  roles:
    - role: ../roles/nginxplus

- name: restart nginx and announce success
  hosts: nginxplus
  remote_user: pulsys
  strategy: linear
  become: true

  tasks:
    - name: nginxplus | restart nginx for realsies
      service: 
        name: nginx
        state: restarted
      tags: always

  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "{{ inventory_hostname }} completed"
        channel: #server-alerts
      tags: always
