# NOTE
# You must use command-line "extra variables" to use this playbook. They are
# used to specify the host group you want to toggle, and the value of
# read_only_mode, e.g.:
# $ ansible-playbook -e "figgy_hosts=postgres_staging" -e "figgy_read_only_mode=true" figgy_toggle_readonly.yml
---
- hosts: "{{ postgresql_hosts }}"
  remote_user: pulsys
  become: true
  vars:
    - deploy_user: "deploy"
  tasks:
    - name: run a database dump
      community.postgresql.postgresql_db:
        login_host:
        login_password:
        login_user:
        owner: '{{ deploy_user }}'
        group: '{{ deploy_user }}'
        mode: 0644
    - name: restart the app
      file:
        state: touch
        path: "/opt/figgy/current/tmp/restart.txt"
      become: true
      become_user: "{{ deploy_user }}"
  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "{{ inventory_hostname }} toggled read-only mode to {{figgy_read_only_mode}}"
        channel: #server-alerts
