---
# by default this playbook runs in the staging environment
# to run in production, pass '-e runtime_env=production'
- name: build the research data site
  hosts: abid_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/researchdata/staging.yml
    - ../group_vars/researchdata/vault.yml
  roles:
    - role: roles/researchdata

  post_tasks:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "{{ inventory_hostname }} completed"
        channel: #server-alerts
