---
- hosts: vireo_staging
  remote_user: pulsys
  become: true
  vars_files:
    - ../site_vars.yml
    - ../group_vars/vireo/common.yml
    - ../group_vars/vireo/staging.yml
    - ../group_vars/vireo/vault.yml

  roles:
    - role: roles/openjdk
    - role: roles/nodejs
    - role: roles/postgresql
    - role: roles/tomcat8
    - role: roles/vireo
