---
# tasks file for pulibrary.deploy-user
- name: Create deploy group
  group:
    name: '{{ deploy_user }}'
    gid: '{{ deploy_user_uid }}'
- name: Create deploy user
  user: 
    name: '{{ deploy_user }}'
    uid: '{{ deploy_user_uid }}'
    group: '{{ deploy_user }}'
    home: '/home/{{ deploy_user }}'
- name: Add SSH keys
  authorized_key:
    user: '{{ deploy_user }}'
    key: '{{ item.key }}'
  with_items: '{{ deploy_ssh_users }}'
- name: Allow deploy user to SSH
  lineinfile: >
              dest=/etc/ssh/sshd_config
              state=present
              backrefs=yes
              regexp='^AllowUsers(.*?)( ?)({{deploy_user}})?$'
              line="AllowUsers\1 {{deploy_user}}"
  notify: Restart ssh
