---
- name: install the dependencies
  apt:
    name: software-properties-common
    state: present
    update_cache: true

- name: add the Brightbox repository
  apt_repository:
    repo: "ppa:brightbox/ruby-ng"
    state: present
    update_cache: true

- name: check ruby version
  command: ruby -v
  register: installed_ruby
  ignore_errors: true
  changed_when: false

- name: install Ruby "{{ ruby_version }}"
  apt:
    name: ["{{ ruby_version }}", "{{ ruby_version }}-dev", "ruby-switch"]
    state: present
  when: installed_ruby.rc !=0 or installed_ruby.stdout.split()[1] != ruby_version
  register: packages_installed

- name: switch to Ruby "{{ ruby_version }}" release for the system default
  command: ruby-switch --set "{{ ruby_version }}"
  when: installed_ruby.rc !=0 or installed_ruby.stdout.split()[1] != ruby_version
  changed_when: false

- name: uninstall bundler to get specific version
  gem:
    name: bundler
    state: absent
    user_install: false
  when: bundler_version is defined

- name: install global bundler, specific version
  gem:
    name: bundler
    version: "{{ bundler_version }}"
    user_install: false
  when: bundler_version is defined

- name: install global bundler, any version
  gem:
    name: bundler
    user_install: false
  when: bundler_version is undefined
